version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile-dev
        container_name: avrae_service
        ports:
            - "58000:8000"
        environment:
            - NODE_ENV=development