name: Build

on:
  [push, pull_request]

permissions:
  contents: read
  id-token: write
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Image
      run: docker build -t avrae-service .
